- folder: /media/ssd/data/oisin_house/data2/
  frames: [712]
  name: saved2_00161_[712]
  scene: saved2_00161
- folder: /media/ssd/data/oisin_house/data2/
  frames: [20]
  name: saved2_00175_[20]
  scene: saved2_00175
- folder: /media/ssd/data/oisin_house/data2/
  frames: [544]
  name: saved2_00187_[544]
  scene: saved2_00187
- folder: /media/ssd/data/oisin_house/data2/
  frames: [41]
  name: saved2_00192_[41]
  scene: saved2_00192
- folder: /media/ssd/data/oisin_house/data2/
  frames: [491]
  name: saved2_00190_[491]
  scene: saved2_00190
- folder: /media/ssd/data/oisin_house/data2/
  frames: [592]
  name: saved2_00180_[592]
  scene: saved2_00180
- folder: /media/ssd/data/oisin_house/data2/
  frames: [27]
  name: saved2_00175_[27]
  scene: saved2_00175
- folder: /media/ssd/data/oisin_house/data2/
  frames: [14]
  name: saved2_00180_[14]
  scene: saved2_00180
- folder: /media/ssd/data/oisin_house/data2/
  frames: [584]
  name: saved2_00185_[584]
  scene: saved2_00185
- folder: /media/ssd/data/oisin_house/data2/
  frames: [516]
  name: saved2_00178_[516]
  scene: saved2_00178
- folder: /media/ssd/data/oisin_house/data2/
  frames: [460]
  name: saved2_00188_[460]
  scene: saved2_00188
- folder: /media/ssd/data/oisin_house/data2/
  frames: [556]
  name: saved2_00187_[556]
  scene: saved2_00187
- folder: /media/ssd/data/oisin_house/data2/
  frames: [30]
  name: saved2_00168_[30]
  scene: saved2_00168
- folder: /media/ssd/data/oisin_house/data2/
  frames: [386]
  name: saved2_00193_[386]
  scene: saved2_00193
- folder: /media/ssd/data/oisin_house/data2/
  frames: [53]
  name: saved2_00196_[53]
  scene: saved2_00196
- folder: /media/ssd/data/oisin_house/data2/
  frames: [960]
  name: saved2_00157_[960]
  scene: saved2_00157
- folder: /media/ssd/data/oisin_house/data2/
  frames: [508]
  name: saved2_00178_[508]
  scene: saved2_00178
- folder: /media/ssd/data/oisin_house/data2/
  frames: [1]
  name: saved2_00161_[1]
  scene: saved2_00161
- folder: /media/ssd/data/oisin_house/data2/
  frames: [66]
  name: saved2_00192_[66]
  scene: saved2_00192
- folder: /media/ssd/data/oisin_house/data2/
  frames: [6]
  name: saved2_00196_[6]
  scene: saved2_00196
- folder: /media/ssd/data/oisin_house/data2/
  frames: [452]
  name: saved2_00188_[452]
  scene: saved2_00188
- folder: /media/ssd/data/oisin_house/data2/
  frames: [38]
  name: saved2_00194_[38]
  scene: saved2_00194
- folder: /media/ssd/data/oisin_house/data2/
  frames: [70]
  name: saved2_00159_[70]
  scene: saved2_00159
- folder: /media/ssd/data/oisin_house/data2/
  frames: [26]
  name: saved2_00193_[26]
  scene: saved2_00193
- folder: /media/ssd/data/oisin_house/data2/
  frames: [545]
  name: saved2_00196_[545]
  scene: saved2_00196
- folder: /media/ssd/data/oisin_house/data2/
  frames: [17]
  name: saved2_00169_[17]
  scene: saved2_00169
- folder: /media/ssd/data/oisin_house/data2/
  frames: [25]
  name: saved2_00159_[25]
  scene: saved2_00159
- folder: /media/ssd/data/oisin_house/data2/
  frames: [28]
  name: saved2_00164_[28]
  scene: saved2_00164
- folder: /media/ssd/data/oisin_house/data2/
  frames: [432]
  name: saved2_00179_[432]
  scene: saved2_00179
- folder: /media/ssd/data/oisin_house/data2/
  frames: [469]
  name: saved2_00189_[469]
  scene: saved2_00189
- folder: /media/ssd/data/oisin_house/data2/
  frames: [54]
  name: saved2_00157_[54]
  scene: saved2_00157
- folder: /media/ssd/data/oisin_house/data2/
  frames: [533]
  name: saved2_00178_[533]
  scene: saved2_00178
- folder: /media/ssd/data/oisin_house/data2/
  frames: [32]
  name: saved2_00190_[32]
  scene: saved2_00190
- folder: /media/ssd/data/oisin_house/data2/
  frames: [641]
  name: saved2_00186_[641]
  scene: saved2_00186
- folder: /media/ssd/data/oisin_house/data2/
  frames: [24]
  name: saved2_00194_[24]
  scene: saved2_00194
- folder: /media/ssd/data/oisin_house/data2/
  frames: [734]
  name: saved2_00161_[734]
  scene: saved2_00161
- folder: /media/ssd/data/oisin_house/data2/
  frames: [13]
  name: saved2_00193_[13]
  scene: saved2_00193
- folder: /media/ssd/data/oisin_house/data2/
  frames: [581]
  name: saved2_00170_[581]
  scene: saved2_00170
- folder: /media/ssd/data/oisin_house/data2/
  frames: [3]
  name: saved2_00167_[3]
  scene: saved2_00167
- folder: /media/ssd/data/oisin_house/data2/
  frames: [494]
  name: saved2_00165_[494]
  scene: saved2_00165
- folder: /media/ssd/data/oisin_house/data2/
  frames: [611]
  name: saved2_00168_[611]
  scene: saved2_00168
- folder: /media/ssd/data/oisin_house/data2/
  frames: [47]
  name: saved2_00189_[47]
  scene: saved2_00189
- folder: /media/ssd/data/oisin_house/data2/
  frames: [464]
  name: saved2_00175_[464]
  scene: saved2_00175
- folder: /media/ssd/data/oisin_house/data2/
  frames: [47]
  name: saved2_00165_[47]
  scene: saved2_00165
- folder: /media/ssd/data/oisin_house/data2/
  frames: [28]
  name: saved2_00176_[28]
  scene: saved2_00176
- folder: /media/ssd/data/oisin_house/data2/
  frames: [613]
  name: saved2_00169_[613]
  scene: saved2_00169
- folder: /media/ssd/data/oisin_house/data2/
  frames: [32]
  name: saved2_00165_[32]
  scene: saved2_00165
- folder: /media/ssd/data/oisin_house/data2/
  frames: [44]
  name: saved2_00164_[44]
  scene: saved2_00164
- folder: /media/ssd/data/oisin_house/data2/
  frames: [20]
  name: saved2_00182_[20]
  scene: saved2_00182
- folder: /media/ssd/data/oisin_house/data2/
  frames: [17]
  name: saved2_00186_[17]
  scene: saved2_00186
- folder: /media/ssd/data/oisin_house/data2/
  frames: [600]
  name: saved2_00158_[600]
  scene: saved2_00158
- folder: /media/ssd/data/oisin_house/data2/
  frames: [14]
  name: saved2_00164_[14]
  scene: saved2_00164
- folder: /media/ssd/data/oisin_house/data2/
  frames: [44]
  name: saved2_00195_[44]
  scene: saved2_00195
- folder: /media/ssd/data/oisin_house/data2/
  frames: [516]
  name: saved2_00177_[516]
  scene: saved2_00177
- folder: /media/ssd/data/oisin_house/data2/
  frames: [44]
  name: saved2_00185_[44]
  scene: saved2_00185
- folder: /media/ssd/data/oisin_house/data2/
  frames: [38]
  name: saved2_00175_[38]
  scene: saved2_00175
- folder: /media/ssd/data/oisin_house/data2/
  frames: [570]
  name: saved2_00170_[570]
  scene: saved2_00170
- folder: /media/ssd/data/oisin_house/data2/
  frames: [303]
  name: saved2_00159_[303]
  scene: saved2_00159
- folder: /media/ssd/data/oisin_house/data2/
  frames: [479]
  name: saved2_00176_[479]
  scene: saved2_00176
- folder: /media/ssd/data/oisin_house/data2/
  frames: [35]
  name: saved2_00179_[35]
  scene: saved2_00179
- folder: /media/ssd/data/oisin_house/data2/
  frames: [506]
  name: saved2_00171_[506]
  scene: saved2_00171
- folder: /media/ssd/data/oisin_house/data2/
  frames: [29]
  name: saved2_00161_[29]
  scene: saved2_00161
- folder: /media/ssd/data/oisin_house/data2/
  frames: [56]
  name: saved2_00180_[56]
  scene: saved2_00180
- folder: /media/ssd/data/oisin_house/data2/
  frames: [18]
  name: saved2_00187_[18]
  scene: saved2_00187
- folder: /media/ssd/data/oisin_house/data2/
  frames: [390]
  name: saved2_00195_[390]
  scene: saved2_00195
- folder: /media/ssd/data/oisin_house/data2/
  frames: [15]
  name: saved2_00171_[15]
  scene: saved2_00171
- folder: /media/ssd/data/oisin_house/data2/
  frames: [471]
  name: saved2_00188_[471]
  scene: saved2_00188
- folder: /media/ssd/data/oisin_house/data2/
  frames: [5]
  name: saved2_00185_[5]
  scene: saved2_00185
- folder: /media/ssd/data/oisin_house/data2/
  frames: [611]
  name: saved2_00182_[611]
  scene: saved2_00182
- folder: /media/ssd/data/oisin_house/data2/
  frames: [29]
  name: saved2_00158_[29]
  scene: saved2_00158
- folder: /media/ssd/data/oisin_house/data2/
  frames: [641]
  name: saved2_00164_[641]
  scene: saved2_00164
- folder: /media/ssd/data/oisin_house/data2/
  frames: [503]
  name: saved2_00196_[503]
  scene: saved2_00196
- folder: /media/ssd/data/oisin_house/data2/
  frames: [447]
  name: saved2_00175_[447]
  scene: saved2_00175
- folder: /media/ssd/data/oisin_house/data2/
  frames: [10]
  name: saved2_00192_[10]
  scene: saved2_00192
- folder: /media/ssd/data/oisin_house/data2/
  frames: [8]
  name: saved2_00195_[8]
  scene: saved2_00195
- folder: /media/ssd/data/oisin_house/data2/
  frames: [16]
  name: saved2_00188_[16]
  scene: saved2_00188
- folder: /media/ssd/data/oisin_house/data2/
  frames: [11]
  name: saved2_00194_[11]
  scene: saved2_00194
- folder: /media/ssd/data/oisin_house/data2/
  frames: [471]
  name: saved2_00194_[471]
  scene: saved2_00194
- folder: /media/ssd/data/oisin_house/data2/
  frames: [45]
  name: saved2_00157_[45]
  scene: saved2_00157
- folder: /media/ssd/data/oisin_house/data2/
  frames: [45]
  name: saved2_00169_[45]
  scene: saved2_00169
- folder: /media/ssd/data/oisin_house/data2/
  frames: [592]
  name: saved2_00185_[592]
  scene: saved2_00185
- folder: /media/ssd/data/oisin_house/data2/
  frames: [18]
  name: saved2_00165_[18]
  scene: saved2_00165
- folder: /media/ssd/data/oisin_house/data2/
  frames: [0]
  name: saved2_00158_[0]
  scene: saved2_00158
- folder: /media/ssd/data/oisin_house/data2/
  frames: [34]
  name: saved2_00182_[34]
  scene: saved2_00182
- folder: /media/ssd/data/oisin_house/data2/
  frames: [614]
  name: saved2_00164_[614]
  scene: saved2_00164
- folder: /media/ssd/data/oisin_house/data2/
  frames: [59]
  name: saved2_00177_[59]
  scene: saved2_00177
- folder: /media/ssd/data/oisin_house/data2/
  frames: [628]
  name: saved2_00168_[628]
  scene: saved2_00168
- folder: /media/ssd/data/oisin_house/data2/
  frames: [8]
  name: saved2_00157_[8]
  scene: saved2_00157
- folder: /media/ssd/data/oisin_house/data2/
  frames: [526]
  name: saved2_00177_[526]
  scene: saved2_00177
- folder: /media/ssd/data/oisin_house/data2/
  frames: [512]
  name: saved2_00190_[512]
  scene: saved2_00190
- folder: /media/ssd/data/oisin_house/data2/
  frames: [24]
  name: saved2_00185_[24]
  scene: saved2_00185
- folder: /media/ssd/data/oisin_house/data2/
  frames: [582]
  name: saved2_00167_[582]
  scene: saved2_00167
- folder: /media/ssd/data/oisin_house/data2/
  frames: [30]
  name: saved2_00177_[30]
  scene: saved2_00177
- folder: /media/ssd/data/oisin_house/data2/
  frames: [507]
  name: saved2_00177_[507]
  scene: saved2_00177
- folder: /media/ssd/data/oisin_house/data2/
  frames: [44]
  name: saved2_00159_[44]
  scene: saved2_00159
- folder: /media/ssd/data/oisin_house/data2/
  frames: [91]
  name: saved2_00189_[91]
  scene: saved2_00189
- folder: /media/ssd/data/oisin_house/data2/
  frames: [24]
  name: saved2_00192_[24]
  scene: saved2_00192
- folder: /media/ssd/data/oisin_house/data2/
  frames: [49]
  name: saved2_00171_[49]
  scene: saved2_00171
- folder: /media/ssd/data/oisin_house/data2/
  frames: [25]
  name: saved2_00195_[25]
  scene: saved2_00195
- folder: /media/ssd/data/oisin_house/data2/
  frames: [36]
  name: saved2_00196_[36]
  scene: saved2_00196
- folder: /media/ssd/data/oisin_house/data2/
  frames: [21]
  name: saved2_00193_[21]
  scene: saved2_00193
- folder: /media/ssd/data/oisin_house/data2/
  frames: [556]
  name: saved2_00180_[556]
  scene: saved2_00180
- folder: /media/ssd/data/oisin_house/data2/
  frames: [32]
  name: saved2_00167_[32]
  scene: saved2_00167
- folder: /media/ssd/data/oisin_house/data2/
  frames: [393]
  name: saved2_00192_[393]
  scene: saved2_00192
- folder: /media/ssd/data/oisin_house/data2/
  frames: [446]
  name: saved2_00179_[446]
  scene: saved2_00179
- folder: /media/ssd/data/oisin_house/data2/
  frames: [396]
  name: saved2_00179_[396]
  scene: saved2_00179
- folder: /media/ssd/data/oisin_house/data2/
  frames: [602]
  name: saved2_00168_[602]
  scene: saved2_00168
- folder: /media/ssd/data/oisin_house/data2/
  frames: [78]
  name: saved2_00194_[78]
  scene: saved2_00194
- folder: /media/ssd/data/oisin_house/data2/
  frames: [36]
  name: saved2_00170_[36]
  scene: saved2_00170
- folder: /media/ssd/data/oisin_house/data2/
  frames: [553]
  name: saved2_00184_[553]
  scene: saved2_00184
- folder: /media/ssd/data/oisin_house/data2/
  frames: [23]
  name: saved2_00184_[23]
  scene: saved2_00184
- folder: /media/ssd/data/oisin_house/data2/
  frames: [48]
  name: saved2_00161_[48]
  scene: saved2_00161
- folder: /media/ssd/data/oisin_house/data2/
  frames: [456]
  name: saved2_00176_[456]
  scene: saved2_00176
- folder: /media/ssd/data/oisin_house/data2/
  frames: [605]
  name: saved2_00169_[605]
  scene: saved2_00169
- folder: /media/ssd/data/oisin_house/data2/
  frames: [400]
  name: saved2_00195_[400]
  scene: saved2_00195
- folder: /media/ssd/data/oisin_house/data2/
  frames: [31]
  name: saved2_00188_[31]
  scene: saved2_00188
- folder: /media/ssd/data/oisin_house/data2/
  frames: [628]
  name: saved2_00182_[628]
  scene: saved2_00182
- folder: /media/ssd/data/oisin_house/data2/
  frames: [53]
  name: saved2_00176_[53]
  scene: saved2_00176
- folder: /media/ssd/data/oisin_house/data2/
  frames: [42]
  name: saved2_00186_[42]
  scene: saved2_00186
- folder: /media/ssd/data/oisin_house/data2/
  frames: [169]
  name: saved2_00190_[169]
  scene: saved2_00190
- folder: /media/ssd/data/oisin_house/data2/
  frames: [60]
  name: saved2_00178_[60]
  scene: saved2_00178
- folder: /media/ssd/data/oisin_house/data2/
  frames: [618]
  name: saved2_00158_[618]
  scene: saved2_00158
- folder: /media/ssd/data/oisin_house/data2/
  frames: [655]
  name: saved2_00186_[655]
  scene: saved2_00186
- folder: /media/ssd/data/oisin_house/data2/
  frames: [53]
  name: saved2_00184_[53]
  scene: saved2_00184
- folder: /media/ssd/data/oisin_house/data2/
  frames: [129]
  name: saved2_00190_[129]
  scene: saved2_00190
- folder: /media/ssd/data/oisin_house/data2/
  frames: [71]
  name: saved2_00189_[71]
  scene: saved2_00189
- folder: /media/ssd/data/oisin_house/data2/
  frames: [57]
  name: saved2_00186_[57]
  scene: saved2_00186
- folder: /media/ssd/data/oisin_house/data2/
  frames: [46]
  name: saved2_00167_[46]
  scene: saved2_00167
- folder: /media/ssd/data/oisin_house/data2/
  frames: [41]
  name: saved2_00187_[41]
  scene: saved2_00187
- folder: /media/ssd/data/oisin_house/data2/
  frames: [11]
  name: saved2_00189_[11]
  scene: saved2_00189
- folder: /media/ssd/data/oisin_house/data2/
  frames: [599]
  name: saved2_00167_[599]
  scene: saved2_00167
- folder: /media/ssd/data/oisin_house/data2/
  frames: [592]
  name: saved2_00169_[592]
  scene: saved2_00169
- folder: /media/ssd/data/oisin_house/data2/
  frames: [6]
  name: saved2_00171_[6]
  scene: saved2_00171
- folder: /media/ssd/data/oisin_house/data2/
  frames: [25]
  name: saved2_00171_[25]
  scene: saved2_00171
- folder: /media/ssd/data/oisin_house/data2/
  frames: [53]
  name: saved2_00158_[53]
  scene: saved2_00158
- folder: /media/ssd/data/oisin_house/data2/
  frames: [324]
  name: saved2_00159_[324]
  scene: saved2_00159
- folder: /media/ssd/data/oisin_house/data2/
  frames: [7]
  name: saved2_00170_[7]
  scene: saved2_00170
- folder: /media/ssd/data/oisin_house/data2/
  frames: [15]
  name: saved2_00170_[15]
  scene: saved2_00170
- folder: /media/ssd/data/oisin_house/data2/
  frames: [9]
  name: saved2_00176_[9]
  scene: saved2_00176
- folder: /media/ssd/data/oisin_house/data2/
  frames: [598]
  name: saved2_00182_[598]
  scene: saved2_00182
- folder: /media/ssd/data/oisin_house/data2/
  frames: [539]
  name: saved2_00184_[539]
  scene: saved2_00184
- folder: /media/ssd/data/oisin_house/data2/
  frames: [514]
  name: saved2_00165_[514]
  scene: saved2_00165
- folder: /media/ssd/data/oisin_house/data2/
  frames: [41]
  name: saved2_00178_[41]
  scene: saved2_00178
- folder: /media/ssd/data/oisin_house/data2/
  frames: [10]
  name: saved2_00184_[10]
  scene: saved2_00184
- folder: /media/ssd/data/oisin_house/data2/
  frames: [15]
  name: saved2_00179_[15]
  scene: saved2_00179
- folder: /media/ssd/data/oisin_house/data2/
  frames: [379]
  name: saved2_00193_[379]
  scene: saved2_00193
- folder: /media/ssd/data/oisin_house/data2/
  frames: [935]
  name: saved2_00157_[935]
  scene: saved2_00157
- folder: /media/ssd/data/oisin_house/data2/
  frames: [38]
  name: saved2_00168_[38]
  scene: saved2_00168
- folder: /media/ssd/data/oisin_house/data2/
  frames: [578]
  name: saved2_00180_[578]
  scene: saved2_00180
- folder: /media/ssd/data/oisin_house/data2/
  frames: [567]
  name: saved2_00187_[567]
  scene: saved2_00187
